# Outline Collection Sync Settings
# ================================
# This file maps Outline collection IDs to local folder paths
# 
# Format:
# collections:
#   collection-id-here:
#     name: "Human readable name"
#     local_path: "/path/to/local/folder"

collections:
  d6e02bc5-cb39-4bd3-8df7-13e022201bee:
    name: "AcmeCorp"
    local_path: "/Users/rk2/Desktop/AcmeCorp"
    
  dc7aa491-9910-499d-b886-03f93e60f196:
    name: "New"
    local_path: "/Users/rk2/Desktop/New"
    
  02409d6d-64a4-4705-a2ae-37303c824ff2:
    name: "Fam"
    local_path: "/Users/rk2/Desktop/Mom"
    

